version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php-blog
  app:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./app/src:/var/www/html/
    depends_on:
      - mysql
    ports:
      - 80:80